apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api-pod
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: containous/whoami
          ports:
            - containerPort: 80
